# Generated by Django 3.2.18 on 2024-02-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('record_type', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='time',
            new_name='timestamp',
        ),
    ]
