# Generated by Django 3.2.18 on 2024-02-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240213_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplerecord',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
