# Generated by Django 3.2.25 on 2024-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplerecord',
            name='file_path',
            field=models.CharField(default='./rubbish/Lab_Report.pdf', max_length=256),
            preserve_default=False,
        ),
    ]
