# Generated by Django 4.1 on 2024-04-19 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_simplerecord_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2024, 4, 20, 0, 39, 42, 563223), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '2. 邮箱验证码',
                'verbose_name_plural': '2. 邮箱验证码',
            },
        ),
    ]
