# Generated by Django 4.1 on 2024-04-19 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 0, 58, 28, 344787), verbose_name='发送时间'),
        ),
    ]
