# Generated by Django 4.1 on 2024-04-19 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 2, 51, 50, 878915), verbose_name='发送时间'),
        ),
    ]
